trigger:
  branches:
    exclude:
      - main
pr:
- main

variables:
- group: codecov

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_12_x:
        node_version: 12.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml
  - template: .azure-pipelines/package.yml

- job: Windows
  pool:
    vmImage: 'windows-latest'
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml

- job: macOS
  pool:
    vmImage: 'macos-latest'
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml