trigger:
  branches:
    include:
    - main

pr: none

variables:
- group: codecov

jobs:
- job: Linux
  pool:
    name: Hosted Ubuntu 1604
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
      node_12_x:
        node_version: 12.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml
  - template: .azure-pipelines/package.yml

- job: Windows
  pool:
    name: Hosted VS2017
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml

- job: macOS
  pool:
    name: Hosted macOS
    demands: npm
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  - template: .azure-pipelines/build.yml
  - template: .azure-pipelines/lint.yml
  - template: .azure-pipelines/test.yml